### ISSUE TITLE
use '.' instead of build for default base_path

### ISSUE THREAD

**Issue by mikaelarguedas** [colcon/colcon-test-result#3]
- Inconvenient for me as a rarely use `build` as the name of the build folder
- It diverges from ament tools
- It diverges from the build and test verbs (that uses '.' by default)

Alternative: Update the readthedocs "ament" documentation to reflect the change in behavior

I don't feel strongly about which approach we take and the second one may be the easiest to change

**Comment by dirk-thomas** [comment]
> Inconvenient for me as a rarely use build as the name of the build folder

It simply matches the default arguments of the `test` verb. If you customize one you will need to customize the other too. Or do you want to see multiple results across all your build folders by default?

If `.` would be used the verb would need to crawl the whole source as well as install space. There should be no test result files in these directories which seems to be wasted time crawling those. Also in case there are xml files found which match the format they would be reported too but are not actually result the user wants to see.

> It diverges from the build and test verbs (that uses '.' by default)

The options in the `build` and `test` verbs are used to find packages. The `test-result` verb uses the location to find result files. So the difference in default value is due to the different semantic. As mentioned above a default value of `.` doesn't seem to be the desired location either.

**Comment by mikaelarguedas** [comment]
It doesnt change the fact that it's inconvenient to not be able to call test result from within a build folder without having to explicitly pass an argument.

I understand the reason for using `build` as the default, hat's why I offered an alternative to document the change in behavior from ament.

Do you have any feedback about the alternative ?

**Comment by dirk-thomas** [comment]
> Do you have any feedback about the alternative ?

I don't see a need to document a different default value on the migrations page - especially since it "just works" with the default values. Please feel free to add whatever note you think makes sense.

**Comment by mikaelarguedas** [comment]
> especially since it "just works" with the default values

I just saw this edit.
Yeah in this case I guess it doesn't need to be clarified as users following the default workflow will not see a difference and people with specific folder structure will figure it out by looking at the help message :+1:
